---
title: "Scientific Computing"
format:
    html:
        embed-resources: true
        theme: solar
---
### By Zephyr

# Introduction
As many scientists know, science usually involves a lot of math. Chemistry involves numerous stoichiometric calculations and planning, computer science involves in-depth application of all sorts of mathematical equations and logic, physics requires even more complex calculations for movements that are usually impacted by multiple intangible forces at once. On top of that, math is a science too, which means it is 100% calculations. The required math is not always very difficult, but humans are very prone to error, and the risk of messing up a sequence of operations increases exponentially when more operations are added. This would not be as much of a problem in and of itself if math was as casual as, for example, grammar. Using the correct verb tenses and proper punctuation and/or spelling can be quite hard for some, but while it is quite an important skill to master, there is almost always no risk of harm to anyone involved if you make a mistake. Math classes are good examples of times and places where solving problems incorrectly is relatively harmless, but math (especially scientific math) in work-related settings is much more likely to be higher-stakes. In economic settings, you might misfile taxes or mess up budgets for various important projects, while miscalculations in architectural work might result in a building collapse, potentially causing hundreds or even thousands of unnecessary deaths. In medical work and biochemistry, even a milligram too much of certain substances can cause a very painful death. I likely do not need to explain why mathematical precision is absolutely life-or-death in hospitals or NASA missions. Given the inherently high risk of many mathematical endeavors, performing calculations by hand is far from ideal, but there is a way to make problem-solving much quicker and safer with relative ease: computers! Since the invention of modern computers and calculators, scientists have been able to solve complicated sets of equations with accuracy and efficiency. On top of that, computers have made it possible to write, peer-review, and publish important studies with incredible speed, even if the people working on any given project are scattered around the globe. Not only do many people now have access to troves of scientific data that they can access at any time, they also have the ability to use professional formatting features that are not typically available on standard writing software: complex equations. Using LaTeX formatting, it becomes very easy to specify what complex equations I am talking about due to the fact that there is a specific “math mode” built in with an entire set of characters that are specifically used in calculus. For example, one can write sets of integrals throughout the entire document while keeping the text professional and legible, despite the fact that there is no key on any keyboard containing the symbol. Definite integrals are even more difficult in this regard, as the numerical range is specified by using vertically parallel subscript and superscript, which is not otherwise possible with standard software. These features are one of the main reasons why scientific computing is absolutely essential for modern-day science worldwide.

### Water and Carbon dioxide yield in grams
$$x * \frac{1}{180.2} * 6 * 18.015$$
$$x * \frac{1}{180.2} * 6 * 40.02$$

# Calculations
For my first demonstration, I have calculated the theoretical yield in grams of water and carbon dioxide that is gained when the compound glucose is burned in oxygen. In the case of handwriting and solving two relatively simple problems, it took me roughly the same amount of time to find the g/mol ratio of all the necessary compounds and either type or write the equation. While writing out the problem, I used a calculator to perform the series of repeated multiplication and division, which is why it took the same amount of time for me to code the equation vs writing it down in this case. This is technically scientific computing as well, though calculators are much more commonplace than using python in the context of scientific mathematics, so I am mostly ignoring that for the purposes of focusing more on the speed of python functions. At any rate, science is already quite a bit inaccessible for many people with certain learning disabilities even without making them do all of their multiplication and long division by hand. Naturally, after finishing the calculations, I got the same results. After that, I could perform another calculation of the same equation with a different amount of glucose as the input. In my calculator, I would have to type the whole equation in again in order to find the answer, while python programming only requires me to replace a single value in order to find the same answer. Already that saves a little bit of time, but that’s only the beginning. With the addition of the copy-paste function used in the Neovim program editing software, I can just as easily create different versions of the same equation with slight alterations in less than 30 seconds. If I tried to calculate 10 different equations with just a calculator, it would take just as much time for me to solve roughly 50 different equations in python, which already adds up to a 500% increase in efficiency, but that is just the tip of the iceberg. Certain packages within python contain functions for even more complex math, including a singular function called solve() that can instantly solve for a missing value if you specify an equation and value to find. Not only does this also take less than thirty seconds as opposed to the 5 or 10 minutes it would take for me to write the whole thing out, but I can also use the copy-paste function to create numerous versions of this equation and solve all of them just as quickly. So if I take 5 minutes to write an equation while I take 30 seconds to solve the same equation via python, that’s a 1000% efficiency increase that continues to stack for each time I have to repeat the process. So that means my efficiency increases at 10x per equation. But that’s still only monomial equations, and the solve() function can just as easily calculate the values of variables in polynomials. This takes a few seconds longer to do, as it requires one to edit a few existing equations and/or make new ones, but that’s still a breeze compared to the fact that the time required to solve an equation manually doubles. Overall, python calculations save a lot of time without as much risk of miscalculating important values.


# DataFrames & Markdown

|Water|  Glucose |
|----:|---------:|
|  10 |  16.6713 |
|  20 |  33.3426 |
|  30 |  50.0139 |
|  50 |  83.3565 |
| 100 | 166.713  |

The compatibility of python with markdown (and quarto markdown) formatting makes it very easy to plug in all the values from any previous equations and quickly put them into labelled datasets. How is anyone supposed to easily interpret unformatted lists of numbers when they are out of the context of paired values? Python makes it easy with markdown and quarto markdown, which are very straightforward formatting styles that have a lot of overlap, making them relatively easy to use even without extensive programming knowledge. They are accessible via a computer’s local terminal and remotely within GitHub’s repository system if you choose to link the two. The potential for scientific publishing is significant; because one can access both publishing tools and mathematical tools in the same software, it is very simple to not only solve complex equations, but also to format the results into easy-to-read tables. This system has more efficiency than any other when it comes to calculation and formatting, as the only other places where one could access the same tools at the same time are other sets of programming software. This kind of efficient, professional formatting makes python and quarto markdown absolutely essential for any data scientist, though many other disciplines may also greatly benefit from the speed and quality of this software. Having tried to make and edit tables on google docs, I can safely say that it is a needlessly complicated process compared to working with quarto markdown. Not only does google docs and other standard software have a massive menu of functions that mostly go unused, but quarto markdown contains the majority of these essential functions, making it far superior in terms of efficiency and quality. As many scientists know, it is not wise to attempt to publish a scientific paper without a group for quality control. Google docs contains options for sharing documents with a whole team of people, but quarto markdown also has even better options for sharing documents. In google docs, there is a history tab that broadly lists large sections of changes made to a document within a certain time frame, but it doesn’t differentiate between editors or offer any separate editing options. On the other hand, using GitHub to share and access a document makes it possible to utilize individual branches, which allow an editor to create a separate version of a document and edit it on their own branch, where they can safely work without worrying about messing up the original document and having to spend hours fixing their mistake. Branches can be shared within a group, which makes it very easy to break into teams for writing certain portions of any given file and then use the merge function to combine all the finalized edits in the main branch. GitHub also uses the commit system, where any and all edits (along with necessary information) can be pushed to GitHub’s remote repository while letting the user choose how many changes to make in any one commit, allowing a full history of the document to be freely accessed at will.


# Matplotlib & Functions

```{python}
import numpy as np
import sympy
from sympy.abc import x
import matplotlib.pyplot as plt
import pandas


sugarwater = 10.0 / 180.2 * 6.0 * 18.015
sugarcarbon = 10.0 / 180.2 * 6.0 * 40.02

solvewater = x / 180.2 * 6.0 * 18.015 - 10
solvecarbon = x / 180.2 * 6.0 * 40.02 - 10

sympy.solve(solvewater, x)
sympy.solve(solvecarbon, x)

solvar = solvewater
sw1 = sympy.solve(solvar, x)
solvar = solvewater - 10
sw2 = sympy.solve(solvar, x)
solvar = solvewater - 20
sw3 = sympy.solve(solvar, x)
solvar = solvewater - 40
sw4 = sympy.solve(solvar, x)
solvar = solvewater - 90
sw5 = sympy.solve(solvar, x)

sw = np.array([sw1, sw2, sw3, sw4, sw5])
wgram = np.array([10.0, 20.0, 30.0, 50.0, 100.0])

wdata = pandas.DataFrame(sw, wgram)

plt.title("Grams Glucose per Grams Water")
plt.plot(sw,wgram)
plt.savefig("sugar.svg")
plt.show()
```

The Matplotlib tool allows for easy creation of graphs using previously formatted data from earlier mathematical equations, which is absolutely essential for any scientist using python and its tool library for publishing purposes. The common software for graph creation do not contain as many mathematical functions as scientists may need, while they also contain little to no publishing tools, which makes formatting unnecessarily difficult. As an example, Excel and google sheets are commonly used to format data tables and quickly turn them into graphs, but the settings are very complex, and in practice they require a lot of specific knowledge about using the specific software in order to be useful. This on its own is a major downside of these pieces of software, but combining that with the lack of functionality in publishing makes them very inconvenient to use, even ignoring the fact that the more powerful Excel is locked behind a Microsoft subscription paywall, making it very inaccessible for scientific publishing. Excel does contain data tables, but they are not able to be quickly moved from Excel files to any other writing software, and the advanced mathematical functions ironically require programming experience in order to function at their best, which makes Excel surprisingly inefficient for the average person to use. In order to properly use Excel, one needs specialized experience, data formatting and only data formatting, and sorted vertical columns of data if one wants to be able to graph anything. With python and its free tools, on the other hand, I can simply make arrays of all the necessary values and use these labelled arrays to quickly make a dataset and graph with the same amount of speed, specialized skills, and drastically increased export functionality. The fact that markdown and quarto markdown even take images, graphs, and entire blocks of python code even with all the additional conveniences make it almost required for scientific publishing. Not only does python and its other tools beat out the specialized data formatting and writing software that you have to spend money for, but it also makes it possible to make your own public website. One can simply publish their own professionally formatted scientific paper on their own website with overwhelming speed and quality. This leaves time for a lot of the more time-consuming aspects of scientific research, such as actually running an experiment, which famously can take years due to the sheer amount of data needed in order to find statistically significant results as well as how long it can take to find a single datapoint. Sciences of all kinds are already a very complicated set of disciplines on their own that require a lot of memorized knowledge, rules, and jargon in order to be able to understand. There is absolutely no need to make scientific publishing any harder than it already is when any given scientist has already proven their prowess in their field.

# In Conclusion
Overall, python and its extensive list of free tools make scientific publishing a less punishing task with increased work speed and quality results. The fact that it has so much mixed functionality makes it far easier than any other combination of software, as it is all accessible from one place with all of the required tools being completely free. The only downside is that a fair amount of knowledge about programming in python and quarto markdown format are required in order to use these tools, which are always available to the public. One of the biggest problems with today’s scientific fields is the lack of accessibility to the general public along with the unnecessary difficulty of publishing professional peer-reviewed research in the first place, though hopefully, this is mostly localized in the United States specifically. The extensive budget cuts to scientific and medical endeavors along with the deliberate gutting of many capable government-owned scientific establishments paints a very bleak picture for the short-term future of scientific research in the United States; paired with the current increasingly repressive anti-intellectual political climate, scientific disciplines are being smothered by the current administration. Even if a different administration were to be quickly put in charge, the unconstitutional handicapping would take generations to undo; with the current hostility towards scientific disciplines and DEI being criminalized across much of the United States, less capable scientists will graduate college, enter the workforce, and perform potentially lifesaving research. On top of that, many previously approved scientific projects have been promptly shut down, meaning years of planning, studying, and research have all gone down the drain. Scientific research projects often take years of preparation and work due to the need for very specific, controlled circumstances, which means that it is impossible to just continue a formal project after it has been unceremoniously cancelled. Unfortunately, these circumstances have led many current and aspiring scientists to work and study abroad in order to perform research in peace, which is very bad for the short-term future of science in the United States, albeit great for the scientists in question and otherwise preserving scientific endeavors. Because of what is commonly referred to as this “brain drain”, it will be much harder for the United States to recover from the current administration’s suppression of scientific disciplines; when skilled professionals leave a country due to decreasing opportunities for a specific discipline, it starts a cycle where a specific discipline continues to decline in that country due to lack of professionals, which further increases the amount of professionals in that discipline leaving the country. All this to say, science is currently very difficult in the United States, so we need all the publishing assistance we can get.
